// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {collectionsvc} from '../models';
import {setup} from '../models';
import {homesvc} from '../models';
import {viewstate} from '../models';

export function AnalyzeDeck(arg1:string,arg2:string):Promise<main.DeckAnalysis>;

export function Collection(arg1:collectionsvc.Query):Promise<main.CollectionPage>;

export function CompareSnapshots():Promise<main.CollectionDiff>;

export function DeckHistory(arg1:string):Promise<Array<main.DeckRevision>>;

export function FirstRun(arg1:boolean,arg2:boolean):Promise<setup.Result>;

export function Home():Promise<homesvc.Model>;

export function ImportCollection():Promise<main.ImportResult>;

export function ImportCollectionFrom(arg1:string):Promise<main.ImportResult>;

export function SaveDeckRevision(arg1:string,arg2:string):Promise<viewstate.State>;

export function SuggestSubstitutions(arg1:string,arg2:string):Promise<main.SubstitutionReport>;

export function Views():Promise<Array<main.View>>;
