// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {collectionsvc} from '../models';
import {main} from '../models';
import {setup} from '../models';
import {homesvc} from '../models';

export function Collection(arg1:collectionsvc.Query):Promise<main.CollectionPage>;

export function CompareSnapshots():Promise<main.CollectionDiff>;

export function FirstRun(arg1:boolean,arg2:boolean):Promise<setup.Result>;

export function Home():Promise<homesvc.Model>;

export function Views():Promise<Array<main.View>>;
