// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {setup} from '../models';
import {homesvc} from '../models';
import {main} from '../models';

export function FirstRun(arg1:boolean,arg2:boolean):Promise<setup.Result>;

export function Home():Promise<homesvc.Model>;

export function Views():Promise<Array<main.View>>;
