// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FirstRun(arg1, arg2) {
  return window['go']['main']['App']['FirstRun'](arg1, arg2);
}

export function Home() {
  return window['go']['main']['App']['Home']();
}

export function Views() {
  return window['go']['main']['App']['Views']();
}
