// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeDeck(arg1, arg2) {
  return window['go']['main']['App']['AnalyzeDeck'](arg1, arg2);
}

export function Collection(arg1) {
  return window['go']['main']['App']['Collection'](arg1);
}

export function CompareSnapshots() {
  return window['go']['main']['App']['CompareSnapshots']();
}

export function DeckHistory(arg1) {
  return window['go']['main']['App']['DeckHistory'](arg1);
}

export function FirstRun(arg1, arg2) {
  return window['go']['main']['App']['FirstRun'](arg1, arg2);
}

export function Home() {
  return window['go']['main']['App']['Home']();
}

export function ImportCollection() {
  return window['go']['main']['App']['ImportCollection']();
}

export function ImportCollectionFrom(arg1) {
  return window['go']['main']['App']['ImportCollectionFrom'](arg1);
}

export function SaveDeckRevision(arg1, arg2) {
  return window['go']['main']['App']['SaveDeckRevision'](arg1, arg2);
}

export function SuggestSubstitutions(arg1, arg2) {
  return window['go']['main']['App']['SuggestSubstitutions'](arg1, arg2);
}

export function Views() {
  return window['go']['main']['App']['Views']();
}
